version: '2'
services:
        balena-cam:
                build: ./balena-cam
                privileged: true
                restart: always
                network_mode: "host"
                labels:
                        io.balena.features.kernel-modules: '1'
        captive-portal-refresh:
                build: ./captive-portal-refresh
                restart: always